### ISSUE TITLE
How to evaluate this model?

### ISSUE THREAD

**Issue by EnJiang** [pawel-n/gomoku-ai#1]
Sorry this is not actually a technical developing question but a rather machine-leaning one.
I myself is developing a AlphaGo-like system to play gomuku, so I'm wondering how well is your system doing currently(say, comparing to a α-β pruning based AI).
If you are still interested in developing a AlphaGo-like Gomuku AI, feel free to contact me via E-mail.

**Comment by pavelchristof** [comment]
It doesn't compare to any AI yet. It's a pretty early state, what's done is mostly the base infrastructure:
  * Pretty efficient board implementation.
  * Basic completely random agent.
  * Rotating replays.
  * TensorFlow code that streams the replays and trains the model. This needed some custom ops to simulate the game.
  * A simple CNN that seems to be able to train. It gets to some ~0.88 accuracy predicting the winner on random games.

It doesn't compare to any AI yet, it needs MCTS. But a lot of initial work is done, the code is efficient  (unlike implementations in python :). The most difficult thing to do will be a fast MCTS implementation.

I might continue this some day if I have more time. I've stopped for now since I've got enough ML at work to satisfy me.

**Comment by pavelchristof** [comment]
Huh, it has some Monte Carlo (not tree search) that I was about to evaluate. But looks like exporting the CNN model (and loading it in C++) is not implemented yet.

![image](https://user-images.githubusercontent.com/1222492/29937966-7ff60af8-8e87-11e7-8895-22a12a5b13ea.png)

**Comment by EnJiang** [comment]
> the code is efficient (unlike implementations in python :)

Yeah right to the point...I found my python code was just literally moving at a snail's pace, so it occurred to me that why should I reinvent the wheel? : )
Anyway, thanks for your reply and I might refer some structures of your nice code here. And hope one day I could find your AI in gomocup top 10.
